### ISSUE TITLE
Dados de Contrato. Informação de Modalidade Perdida?

### ISSUE THREAD

**Issue by carlosandrade** [okfn-brasil/gastos_abertos_dados#1]
Pensei em deixar o comentário aqui para não se perder em lista de e-mails. Pelo site parece que é possível filtrar por modalidade, apesar de não demonstrar na tabela. Houve alguma tentativa de pesquisar por modalidade para obter todos os dados e explicitamente introduzir a categoria na tabela? Do contrário perdemos essa informação.

**Comment by aivuk** [comment]
Passa o link do site está se referindo e é sempre melhor comentar qual fonte dos dados é a dúvida.

**Comment by carlosandrade** [comment]
https://github.com/okfn-brasil/gastos_abertos_dados/blob/master/Contratos/fonte

**Comment by aivuk** [comment]
Mas já conseguimos filtrar por Modalidade:

http://site.gastosabertos.org/contratos/#?modalidade=PREG%C3%83O+PRESENCIAL

**Comment by carlosandrade** [comment]
Ooops isso que dá usar a referência velha para abrir issue haha :+1:
